name: Unzip ZIP File

on:
  push:
    paths:
      - 'project-bolt-github-x9dqhdxn.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Unzip project-bolt-github-x9dqhdxn.zip
        run: |
          unzip project-bolt-github-x9dqhdxn.zip -d extracted
          rm project-bolt-github-x9dqhdxn.zip
          mv extracted/* ./
          rm -r extracted

      - name: Commit unzipped files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Unzipped project ZIP"
          git push
