name: Manual Unzip

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Unzip ZIP file with permissions fix
        run: |
          unzip -o -q project-bolt-github-x9dqhdxn.zip -d extracted
          chmod -R u+rw extracted
          rm project-bolt-github-x9dqhdxn.zip
          mv extracted/* ./
          rm -r extracted

      - name: Commit unzipped files (if any)
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Manually unzipped ZIP file"
            git push
          fi
